/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Use environment variables if available (for Vercel deployment)
// Otherwise fall back to hardcoded values (for Figma Make)
export const projectId = import.meta.env?.VITE_SUPABASE_PROJECT_ID || "vkkyvswfwowndezjkkuk"
export const publicAnonKey = import.meta.env?.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZra3l2c3dmd293bmRlempra3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MTE5MjIsImV4cCI6MjA3NjM4NzkyMn0.0Rh8DuxYRX-7HAZhHfyXiNAMRgeuoahLlf10e3s-6E8"
