/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vkkyvswfwowndezjkkuk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZra3l2c3dmd293bmRlempra3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MTE5MjIsImV4cCI6MjA3NjM4NzkyMn0.0Rh8DuxYRX-7HAZhHfyXiNAMRgeuoahLlf10e3s-6E8"